### ISSUE TITLE
two stream fusion

### ISSUE THREAD

**Issue by yanpeilun** [bryanyzhu/two-stream-pytorch#19]
Hi bryanyzhu:
thanks for your opensource code!
the spatial and temporal stream were ahieved. I want to know ,wheter the fusion of these two steram  is reached ??.I didn't find the relevant source code under the project.

**Comment by bryanyzhu** [comment]
I didn't do the fusion, but I think it should reach the performance. I am working on other projects at this moment. 

The source code is here, the [spatial result](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/scripts/eval_ucf101_pytorch/spatial_demo.py#L86) is saved in a npy file, and the [temporal result](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/scripts/eval_ucf101_pytorch/temporal_demo.py#L88) is saved in another npy file. You just need to load these two files, weighted averaging them, and get the final fusion result. It should be easy.

**Comment by Benjiou** [comment]
Hi @yanpeilun and @bryanyzhu,

1) Have you stored somewhere  the `ucf101_s1_rgb_resnet152.npy` and `ucf101_s1_flow_resnet152.npy` scores. If yes do you mind sharing them ?

2) What is the final score after fusing RGB and Flow scores ?

Thank you a lot

**Comment by bryanyzhu** [comment]
Hi @Benjiou , 

1. The .npy files are generated using my provided pre-trained models. The code is also provided. You can run the code under this directory (https://github.com/bryanyzhu/two-stream-pytorch/tree/master/scripts/eval_ucf101_pytorch) to get them. 

2. I don't know the fusing scores, because I didn't do it. You can try it. Thank you.
