### ISSUE TITLE
What's your next plan?

### ISSUE THREAD

**Issue by qijiezhao** [bryanyzhu/two-stream-pytorch#2]
Hi, @bryanyzhu : 

I recently write a same repo about two-stream video classification using PyTorch, I realized 85.5% of spatial frame's accuracy on split1 of UCF101 last month. I want to cooperate with you, help you build a more useful framework. (implement some famous works, such as TSN, C3D and so on), so I want to communicate more with you if you are interested in my thought.

**Comment by bryanyzhu** [comment]
Hi, sorry for the late reply. Your result is great, which model do you use to achieve 85.5%? And BTW, does your temporal stream work? because for my implementation now, the temporal stream doesn't work so well due to different preprocessing. I am definitely interested in cooperating with you to build a better framework. My email is yzhu25@ucmerced.edu, let's discuss through email first.
