### ISSUE TITLE
code  undestanding

### ISSUE THREAD

**Issue by yanpeilun** [bryanyzhu/two-stream-pytorch#21]
https://github.com/bryanyzhu/two-stream-pytorch/blob/6b0b4ec29739cf0ba030cee829a251e46e8fd4ae/models/flow_resnet.py#L167

hello bryanyzhu: 
I'm reading your code,but i can't understand the effect of this function.  Could you please explain it briefly?
thanks

**Comment by bryanyzhu** [comment]
Oh, that is because when you build the temporal stream network, the channels of your first conv layer is 20 (suppose you give 10 optical flow images). But pre-trained models on ImageNet only has 3 channels in the first conv layer (because it is RGB image). 

So as proposed in this [paper](https://arxiv.org/abs/1507.02159), we first average the filters in the 3 channel to 1 channel, and repeat this channel 20 times to serve as the initialization of the first conv layer of our temporal stream. Hope this is clear.

**Comment by yanpeilun** [comment]
@bryanyzhu Thank you so  much, I understand what it means
