### ISSUE TITLE
Is there a demo to recognition the action?

### ISSUE THREAD

**Issue by MILOTIDE** [bryanyzhu/two-stream-pytorch#25]
Hi, may I know whether there is a demo to detect the human action in a short video?Not giving the accuracy of this net,but the prediction just like jump, run ,fall ,dance.Thanks.

**Comment by bryanyzhu** [comment]
Hi, you can modify [this line](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/scripts/eval_ucf101_pytorch/temporal_demo.py#L78) a little bit to get what you want. 

This line give you the predicted label, which is the class id. Instead of calculating accuracy, you can find the class name in this [file](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/datasets/ucf101_splits/classInd.txt), and print it out. You will get the predictions.

**Comment by MILOTIDE** [comment]
Thanks for your apply. I met another problem. I cannot install the dense flow,it looks like the branch of opencv3.1, but when make it, there are so many errors. There are many functions that support by opencv2 not by opencv3.1. I don't know why, can you help me? Thanks

**Comment by MILOTIDE** [comment]
Just Like the error:
xx/dense_flow/src/dense_warp_flow_gpu.cpp:33:2: error: ‘SurfFeatureDetector’ was not declared in this scope
I found that SurfFeatureDetector is used by opencv2, in opencv3 it should be: Ptr<SURF> detector = SURF::create( )
So why the dense flow is the branch of opencv3.1,but the code is compatible with opencv2?

**Comment by bryanyzhu** [comment]
Hi, please check this repo, https://github.com/yjxiong/dense_flow/tree/opencv-3.1, to see if you can successfully compile and run their demo. Let me how it goes. Because I follow their repo to write the code, and it seems fine.
