### ISSUE TITLE
speed and pytorch version

### ISSUE THREAD

**Issue by linhezheng19** [bryanyzhu/two-stream-pytorch#37]
excuse me, i want to known the speed of your project, and the pytroch version. if you do not mind, and the other requirement

**Comment by bryanyzhu** [comment]
For the pytorch version, it should be 0.2 or 0.3 because this is a project developed 2 years ago. But if you want to work with the latest pytorch version, it should be fine or requiring very minimum of change because this repo doesn't have any customized layer or operation.   

Since this is a standard classification problem, the speed is just the network's speed. I mean, if you know resnet50's speed, our model should have the same speed. 

Other requirements may be just opencv.

**Comment by linhezheng19** [comment]
can we use the python-opencv, not the make version from source code?

**Comment by bryanyzhu** [comment]
If you want to extract optical flow, you need build from source.

But if you only want to train the model, no matter spatial stream or temporal stream, python-opencv is enough.

**Comment by linhezheng19** [comment]
ok, thank you!
